<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../CreatorControlSuite.Core/CreatorControlSuite.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ChatOverlay\**\*" />
  </ItemGroup>
</Project>