import type { WidgetDefaults } from "../types";

export const WIDGET_DEFAULTS: Record<string, WidgetDefaults> = {
  online: { w: 280, h: 90, props: { showClock: true, showUptime: true } },
  alert: { w: 480, h: 140, props: { durationMs: 5000, maxQueue: 5 } },
  music: {
    w: 950,
    h: 188,
    props: {
      variant: "classic",
      sizePreset: "standard",
      showTitle: true,
      showArtist: true,
      showAlbumCover: true,
      showProgress: true,
      hideWhenPaused: false
    }
  },
  chat: {
    w: 420,
    h: 560,
    props: {
      showTwitchEvents: true,
      maxLines: 80,
      backgroundType: "None",
      backgroundColor: "#000000",
      backgroundOpacityPercent: 55,
      paddingPx: 12,
      borderRadiusPx: 12,
      gapPx: 6,
      fontSizePx: 18,
      fontFamily: "Segoe UI, system-ui, sans-serif"
    }
  },
  "ending-stats": {
    w: 980,
    h: 220,
    props: {
      variant: "classic",
      showTitle: true
    }
  },
  text: {
    w: 480,
    h: 120,
    props: {
      content: "Text",
      fontSizePx: 48,
      fontFamily: "Segoe UI, system-ui, sans-serif",
      color: "#ffffff",
      align: "center",
      verticalAlign: "middle",
      fontWeight: "700",
      letterSpacingPx: 0,
      lineHeight: 1.15,
      textShadow: "0 2px 12px rgba(0,0,0,.55)"
    }
  },
  image: {
    w: 400,
    h: 400,
    props: {
      src: "",
      fit: "contain",
      opacity: 1,
      borderRadiusPx: 0,
      objectPosition: "center"
    }
  },
  countdown: {
    w: 520,
    h: 160,
    props: {
      variant: "classic",
      format: "mm:ss",
      showLabel: true,
      hideWhenIdle: false,
      fontSizePx: 72,
      color: "#ffffff",
      align: "center"
    }
  },
  socials: {
    w: 280,
    h: 72,
    props: {
      platform: "twitch",
      handle: "",
      url: "",
      iconUrl: "",
      label: "",
      variant: "pills",
      showLabels: true,
      showHandles: true,
      colorMode: "brand",
      iconLibrary: "svg",
      iconSize: 36,
      gap: 12,
      iconColor: "#ffffff"
    }
  },
  "partner-roulette": {
    w: 320,
    h: 320,
    props: {
      images: [],
      intervalMs: 4000,
      transition: "fade",
      transitionMs: 500,
      fit: "contain",
      borderRadiusPx: 12,
      objectPosition: "center"
    }
  },
  spotify: {
    w: 950,
    h: 188,
    props: {
      variant: "classic",
      sizePreset: "standard",
      showTitle: true,
      showArtist: true,
      showAlbumCover: true,
      showProgress: true,
      hideWhenPaused: false
    }
  },
  "goal-bar": {
    w: 560,
    h: 88,
    props: {
      variant: "classic",
      sizePreset: "standard",
      kind: "followers",
      label: "Follower Goal",
      target: 200,
      showLabel: true,
      showCurrent: true,
      showTarget: true,
      showPercent: true,
      showRemaining: false,
      barHeightPx: 14,
      borderRadiusPx: 10,
      fillStyle: "gradient",
      animateFill: true,
      color: "#ff7a00",
      color2: "#ffb36b",
      trackColor: "rgba(255,255,255,.12)",
      textColor: "#ffffff",
      fontSizePx: 16,
      hideWhenComplete: false,
      pulseOnProgress: false
    }
  },
  "event-ticker": {
    w: 1100,
    h: 56,
    props: {
      variant: "classic",
      sizePreset: "standard",
      sources: ["follow", "subscribe", "raid", "cheer"],
      maxItems: 20,
      order: "newest",
      template: "{user} · {type}",
      separator: "  •  ",
      showIcon: true,
      showType: true,
      showTime: false,
      mode: "marquee",
      speed: 40,
      hideWhenEmpty: false,
      uppercase: false,
      showAvatars: false,
      color: "#ffffff",
      color2: "#ff7a00",
      bgColor: "#111111",
      bgOpacity: 0.55,
      borderRadiusPx: 10,
      gapPx: 12,
      paddingPx: 10,
      fontSizePx: 16
    }
  },
  "viewer-count": {
    w: 260,
    h: 80,
    props: {
      variant: "classic",
      sizePreset: "standard",
      label: "Viewer",
      showLabel: true,
      showIcon: true,
      showPeak: true,
      showDelta: false,
      format: "plain",
      align: "center",
      color: "#ffffff",
      color2: "#ff7a00",
      bgColor: "#111111",
      bgOpacity: 0.45,
      borderRadiusPx: 12,
      fontSizePx: 28,
      iconSize: 22,
      hideWhenOffline: false,
      pulseOnChange: false
    }
  },
  "lower-third": {
    w: 560,
    h: 120,
    props: {
      variant: "broadcast",
      sizePreset: "standard",
      name: "Streamer",
      subtitle: "Just Chatting",
      tag: "LIVE",
      avatarUrl: "",
      showAvatar: true,
      showSubtitle: true,
      showTag: true,
      showAccentBar: true,
      layout: "left",
      avatarShape: "circle",
      accentPosition: "left",
      entrance: "none",
      color: "#ff7a00",
      textColor: "#ffffff",
      subtitleColor: "rgba(255,255,255,.75)",
      tagColor: "#111111",
      bgColor: "#111111",
      bgOpacity: 0.72,
      borderRadiusPx: 12,
      paddingPx: 14,
      gapPx: 12,
      nameSizePx: 28,
      subtitleSizePx: 16
    }
  },
  "qr-code": {
    w: 220,
    h: 260,
    props: {
      variant: "classic",
      sizePreset: "md",
      url: "",
      caption: "Scan me",
      showCaption: true,
      captionPosition: "below",
      errorCorrection: "M",
      quietZone: 2,
      fg: "#111111",
      bg: "#ffffff",
      logoUrl: "",
      showLogo: false,
      borderRadiusPx: 12,
      paddingPx: 12,
      frame: true,
      color: "#ff7a00",
      invert: false,
      hideWhenEmptyUrl: false
    }
  },
  "brb-panel": {
    w: 1060,
    h: 420,
    props: {
      variant: "classic",
      sizePreset: "brb",
      mode: "brb",
      title: "",
      message: "Gleich geht's weiter",
      showTitle: true,
      showMessage: true,
      showIcon: false,
      icon: "",
      iconUrl: "",
      showCountdown: true,
      countdownFormat: "mm:ss",
      align: "center",
      stackGap: 12,
      showProgressBar: true,
      color: "#ff7a00",
      textColor: "#ffffff",
      messageColor: "rgba(255,255,255,.8)",
      bgColor: "#0b0b0b",
      bgOpacity: 0.72,
      borderRadiusPx: 16,
      titleSizePx: 48,
      messageSizePx: 20,
      uppercaseTitle: true,
      hideWhenCountdownIdle: false
    }
  },
  "announcement-bar": {
    w: 1200,
    h: 64,
    props: {
      variant: "classic",
      sizePreset: "standard",
      message: "Willkommen im Stream!",
      prefix: "",
      icon: "",
      showIcon: false,
      showPrefix: false,
      scroll: true,
      speed: 40,
      direction: "ltr",
      repeatGap: 48,
      color: "#ffffff",
      color2: "#ff7a00",
      bgColor: "#111111",
      bgOpacity: 0.65,
      borderRadiusPx: 10,
      paddingPx: 12,
      align: "center",
      fontSizePx: 18,
      uppercase: false,
      showAccentDot: true,
      hideWhenEmpty: false
    }
  },
  "fruppis-landadel": {
    w: 560,
    h: 200,
    props: {
      variant: "gentry",
      sizePreset: "standard",
      name: "Peter Saul",
      title: "Anwalt",
      subtitle: "Cambridge · Landadel",
      tag: "ZWIELICHTIG",
      quote: "Weiße Schuhe, rote Hose, blauer Hoodie.",
      stats: "1,75 m · sportlich",
      avatarUrl: "",
      showFigure: true,
      showAvatar: false,
      showName: true,
      showTitle: true,
      showSubtitle: true,
      showTag: true,
      showQuote: true,
      showStats: true,
      showAccentBar: true,
      showSidePart: true,
      layout: "figure-left",
      mood: "shady",
      entrance: "none",
      hoodieColor: "#2E6BB0",
      pantsColor: "#B91C3A",
      shoeColor: "#F2EEE6",
      hairColor: "#E8D5A3",
      eyeColor: "#4A90D9",
      skinColor: "#E8C4A8",
      color: "#2E6BB0",
      color2: "#B91C3A",
      textColor: "#F2EEE6",
      subtitleColor: "#C8B890",
      tagColor: "#E8D5A3",
      quoteColor: "#A8B8C8",
      bgColor: "#080C12",
      bgOpacity: 0.82,
      borderRadiusPx: 14,
      paddingPx: 16,
      gapPx: 14,
      nameSizePx: 28,
      titleSizePx: 16,
      quoteSizePx: 13,
      shadeIntensity: 0.45,
      uppercaseName: false,
      hideWhenEmpty: false
    }
  },
  "bubatz-cantina": {
    w: 480,
    h: 220,
    props: {
      mode: "sign",
      variant: "cantina-neon",
      sizePreset: "standard",
      title: "biomilchs Bubatz Cantina",
      subtitle: "Open late · Orbit Sector 7",
      message: "Blue Milk & Hyperspace Haze — heute happy hour",
      menuLines:
        "Blue Milk · 4 Credits\nBantha Burger · 8 Credits\nHyperspace Haze · 12 Credits\nCantina Special · 15 Credits",
      statusLabel: "Special",
      statusValue: "Bubatz live",
      icon: "🌿",
      showLeaf: true,
      showStars: true,
      showTitle: true,
      showSubtitle: true,
      showMessage: true,
      showMenu: true,
      showStatus: true,
      scroll: false,
      speed: 40,
      repeatGap: 48,
      color: "#5CDB6A",
      color2: "#2EE6C5",
      color3: "#E8B84A",
      textColor: "#EAF6FF",
      mutedColor: "#9EC4D8",
      bgColor: "#060B14",
      bgOpacity: 0.88,
      borderRadiusPx: 16,
      paddingPx: 20,
      gapPx: 10,
      titleSizePx: 28,
      bodySizePx: 15,
      uppercase: false,
      pulseLeaf: true,
      twinkleStars: true,
      hideWhenEmpty: false
    }
  },
  "animated-background": {
    w: 1920,
    h: 1080,
    props: {
      variant: "cyber",
      sizePreset: "fullscreen",
      color: "#00f0ff",
      color2: "#ff00aa",
      color3: "#7a00ff",
      speed: 1,
      intensity: 0.85,
      opacity: 1,
      density: 1,
      borderRadiusPx: 0,
      vignette: true,
      paused: false
    }
  }
};
